In [1]:
import numpy
from numpy.ma.core import identity

print(numpy.array([1,2,3,4,5,6]))
print(numpy.array([1,2,3,4,5,6]))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [1]:
import numpy as np



In [2]:
arr = np.array([[1,2,3,4,5,6]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(arr.itemsize)

[[1 2 3 4 5 6]]
(1, 6)
6
2
int64
8


In [3]:
arr = np.array(([1,2,3,4,5,6,7,8,9]))
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr2= np.array([[[1],[1]],[[1],[1]]])
print(arr2)
print("deminsions are:,",arr2.ndim)
print(arr2.shape)


[[[1]
  [1]]

 [[1]
  [1]]]
deminsions are:, 3
(2, 2, 1)


In [5]:
numbers = np.array([20,34,56,77,88])
print(numbers*2)


[ 40  68 112 154 176]


In [6]:
arr3 = np.array([
    [[1,2],[3,4]],
    [[3,4],[5,6]]
])
print(arr3)

[[[1 2]
  [3 4]]

 [[3 4]
  [5 6]]]


In [7]:
print(np.array(arr3))
print(arr3.shape)
print(arr3.ndim)
print(arr3.dtype)

[[[1 2]
  [3 4]]

 [[3 4]
  [5 6]]]
(2, 2, 2)
3
int64


In [8]:
matrix=np.zeros((3,3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
print(np.identity(3))
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
np.full((3,3),100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [12]:
np.arange(10)
np.arange(2,45,4)
np.arange(st)

NameError: name 'st' is not defined