In [1]:
import numpy
print(numpy.array([1,2,3,4,5,6]))
print(numpy.array([1,2,3,4,5,6]))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [2]:
import numpy as np



In [11]:
arr = np.array([[1,2,3,4,5,6]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(arr.itemsize)

[[1 2 3 4 5 6]]
(1, 6)
6
2
int64
8


In [12]:
arr = np.array(([1,2,3,4,5,6,7,8,9]))
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
arr2= np.array([[[1],[1]],[[1],[1]]])
print(arr2)
print("deminsions are:,",arr2.ndim)
print(arr2.shape)


[[[1]
  [1]]

 [[1]
  [1]]]
deminsions are:, 3
(2, 2, 1)


In [19]:
numbers = np.array([20,34,56,77,88])
print(numbers*2)


[ 40  68 112 154 176]


In [23]:
arr3 = np.array([
    [[1,2],[3,4]],
    [[3,4],[5,6]]
])
print(arr3)

[[[1 2]
  [3 4]]

 [[3 4]
  [5 6]]]


In [24]:
print(np.array(arr3))
print(arr3.shape)
print(arr3.ndim)
print(arr3.dtype)

[[[1 2]
  [3 4]]

 [[3 4]
  [5 6]]]
(2, 2, 2)
3
int64
