In [3]:
import numpy as np



In [14]:
arr = np.array([12,3,4,5],ndmin=2)

In [ ]:
print(arr)
print(arr.ndim)
print(arr.shape)

[[12  3  4  5]]
2
(1, 4)


In [19]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2 = np.array([[[1],[1]],[[1],[1]]])

In [33]:
print(arr2)
print(arr2.shape)
print("dimesnerions are: ,",arr2.ndim)

[[[1]
  [1]]

 [[1]
  [1]]]
(2, 2, 1)
dimesnerions are: , 3


In [7]:
arr =np.array([1,2,3,4])

In [8]:
arr

array([1, 2, 3, 4])

In [ ]:
"""
Numpy Again  
"""

'\n\nNumpy Again \n\n\n'

In [5]:
import time
import numpy as np

# 1. Setup data size (10 million items)
DATA_SIZE = 10_000_000

# Initialize a standard Python list and a NumPy array
py_list = list(range(DATA_SIZE))
np_array = np.arange(DATA_SIZE)

print(f"Benchmarking operations over {DATA_SIZE:,} elements...\n")

# --- TEST 1: SUMMATION ---
# Measure Python list sum
start_time = time.time()
list_sum = sum(py_list)
list_sum_time = time.time() - start_time

# Measure NumPy array sum
start_time = time.time()
array_sum = np.sum(np_array)
array_sum_time = time.time() - start_time

print("### Test 1: Summing Elements ###")
print(f"Python List time: {list_sum_time:.5f} seconds")
print(f"NumPy Array time: {array_sum_time:.5f} seconds")
print(f"👉 NumPy is {list_sum_time / array_sum_time:.1f}x faster\n")


# --- TEST 2: ELEMENT-WISE MULTIPLICATION ---
# Measure Python list multiplication (requires a loop/list comprehension)
start_time = time.time()
list_mult = [x * 2 for x in py_list]
list_mult_time = time.time() - start_time

# Measure NumPy array multiplication (uses optimized vectorization)
start_time = time.time()
array_mult = np_array * 2
array_mult_time = time.time() - start_time

print("### Test 2: Multiplying Elements by 2 ###")
print(f"Python List time: {list_mult_time:.5f} seconds")
print(f"NumPy Array time: {array_mult_time:.5f} seconds")
print(f"👉 NumPy is {list_mult_time / array_mult_time:.1f}x faster\n")


Benchmarking operations over 10,000,000 elements...

### Test 1: Summing Elements ###
Python List time: 0.28637 seconds
NumPy Array time: 0.04044 seconds
👉 NumPy is 7.1x faster

### Test 2: Multiplying Elements by 2 ###
Python List time: 0.43839 seconds
NumPy Array time: 0.01956 seconds
👉 NumPy is 22.4x faster



In [6]:
import numpy as np



In [7]:
li = [1,2,3,4,5]
arr = np.array([1,2,3,4,5])

In [8]:
for i in li:
    print(i*2)

2
4
6
8
10


In [16]:
arr

array([1, 2, 3, 4, 5])

In [14]:
arr.ndim

1

In [15]:
arr.shape

(5,)

In [25]:
arr2D = np.array([1,2,3,4],ndmin=4)

In [26]:
print(arr2D)
print(arr2D.shape)

[[[[1 2 3 4]]]]
(1, 1, 1, 4)


In [28]:
arrMultiDimension = np.array([[1,2,3,4],[5,6,7,8]])

In [30]:
arrMultiDimension.shape

(2, 4)

In [34]:
arr3D =np.array([[[1,2,3,4],[5,6,7,8],[5,6,7,8]],[[1,2,3,4],[5,6,7,8],[5,6,7,8]]])

In [ ]:
arr3D
"""
array([[7, 8],
        [7, 8]],

        [7, 8],
        [7, 8]]])
"""

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8],
        [5, 6, 7, 8]]])

In [38]:
arr2D = np.array([[1,2,3,4],[5,6,7,8]])

In [39]:
arr2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [51]:
arr2D[:,1:3]

array([[2, 3],
       [6, 7]])

In [56]:
arr3D =np.array([[[1,2,3,4],[5,6,7,8],[5,6,7,8]],[[1,2,3,4],[5,6,7,8],[5,6,7,8]]])
arr3D

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8],
        [5, 6, 7, 8]]])

In [55]:
arr3D[0:,1:,2:]

array([[[7, 8],
        [7, 8]],

       [[7, 8],
        [7, 8]]])

In [57]:
Arr = np.array(range(0,100))

In [58]:
Arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [61]:
evenList = []
oddList = []
for i in Arr:
    if i%2 == 0:
        evenList.append(i)
    else:
        oddList.append(i)

In [65]:
evenArray = np.array(evenList)
oddArrat = np.array(oddList)

In [67]:
evenArray
oddArrat

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [71]:
evenArray = Arr[Arr%2==0]
oddArray = Arr[Arr%2!=0]

In [73]:
print(evenArray)
print(oddArray)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [76]:
evenArray[1]=5 

In [78]:
studentMarks = np.array([25 , 50, 80 , 90 ,10 , 33])
# 80 > A
# 80 < B
# 50 < C
# 33 <= F 

In [94]:
gradeList = []
for i in studentMarks:
    if i >=80:
        gradeList.append("A")
    elif i<80 and i >= 50:
        gradeList.append("B")
    elif i>= 33 and i < 50:
        gradeList.append("C")
    elif i<=33:
        gradeList.append("F")
gradeArray = np.array(gradeList)


In [95]:
print(studentMarks)
print(gradeArray)

[25 50 80 90 10 33]
['F' 'B' 'A' 'A' 'F' 'C']


In [93]:
studentMarks = np.array([25 , 50, 80 , 90 ,10 , 33])

condition = [(studentMarks >=80),(studentMarks >=50),(studentMarks>=33)]
grade = ["A","B","C"]
gradeArray = np.select(condition,grade,default="F")
print(gradeArray)

['F' 'B' 'A' 'A' 'F' 'C']


In [102]:
arr

(array([0, 1, 2, 3]),)