In [1]:
import numpy
from numpy.ma.core import identity

print(numpy.array([1,2,3,4,5,6]))
print(numpy.array([1,2,3,4,5,6]))

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [1]:
import numpy as np



In [2]:
arr = np.array([[1,2,3,4,5,6]])
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)
print(arr.itemsize)

[[1 2 3 4 5 6]]
(1, 6)
6
2
int64
8


In [3]:
arr = np.array(([1,2,3,4,5,6,7,8,9]))
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr2= np.array([[[1],[1]],[[1],[1]]])
print(arr2)
print("deminsions are:,",arr2.ndim)
print(arr2.shape)


[[[1]
  [1]]

 [[1]
  [1]]]
deminsions are:, 3
(2, 2, 1)


In [5]:
numbers = np.array([20,34,56,77,88])
print(numbers*2)


[ 40  68 112 154 176]


In [6]:
arr3 = np.array([
    [[1,2],[3,4]],
    [[3,4],[5,6]]
])
print(arr3)

[[[1 2]
  [3 4]]

 [[3 4]
  [5 6]]]


In [7]:
print(np.array(arr3))
print(arr3.shape)
print(arr3.ndim)
print(arr3.dtype)

[[[1 2]
  [3 4]]

 [[3 4]
  [5 6]]]
(2, 2, 2)
3
int64


In [8]:
matrix=np.zeros((3,3))
print(matrix)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [9]:
print(np.ones((3,3)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [10]:
print(np.identity(3))
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
np.full((3,3),100)

array([[100, 100, 100],
       [100, 100, 100],
       [100, 100, 100]])

In [12]:
np.arange(10)
np.arange(2,45,4)
np.arange(st)

NameError: name 'st' is not defined

In [24]:
a=np.array([1,2,3,3,4,5,5,6,7,8])
print(a)
print(a.shape)
print(a.size)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a+10)
print(a**2)

[1 2 3 3 4 5 5 6 7 8]
(10,)
10
1
int64
8
[11 12 13 13 14 15 15 16 17 18]
[ 1  4  9  9 16 25 25 36 49 64]


In [29]:
print(a[0])
print(a[a>1])
print(a[1:4])

1
[2 3 3 4 5 5 6 7 8]
[2 3 3]


In [37]:
matrix = np.array([[1,2,3,3],[4,5,6,7]])
print(matrix)
print(matrix.shape)
print(matrix[0,1])
print(matrix.sum())
print(matrix.mean())
print(matrix.min())
print(matrix.max())
print(matrix.T)

[[1 2 3 3]
 [4 5 6 7]]
(2, 4)
2
31
3.875
1
7
[[1 4]
 [2 5]
 [3 6]
 [3 7]]


In [43]:
np.random.rand(3)


array([0.89139346, 0.88591008, 0.35619031])

In [44]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [45]:
np.dot(a,a)

np.int64(238)

In [46]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 1.73205081, 2.        ,
       2.23606798, 2.23606798, 2.44948974, 2.64575131, 2.82842712])

In [50]:
import numpy as np
import time
list = list(range(1000))
arr1= np.arange(1000)

TypeError: 'list' object is not callable

In [51]:
np.zeros((5))

array([0., 0., 0., 0., 0.])

In [52]:
np.ones((5))

array([1., 1., 1., 1., 1.])

In [53]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [54]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [57]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [58]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
np.random.randn(3,4)

array([[-1.38210394e+00, -1.09401012e+00,  4.56112388e-01,
        -3.30387028e-01],
       [-1.13492279e+00,  3.52050127e+00,  3.04820632e-01,
        -1.69602684e+00],
       [-1.98585058e+00, -4.13234452e-04,  1.53100516e-01,
         1.01256963e-02]])

In [60]:
np.random.randn(4)

array([-0.24362982, -0.42457211,  1.23035192, -0.04966699])

In [61]:
matrix[0,1]

np.int64(2)

In [62]:
matrix[:,1]

array([2, 5])