In [4]:
from fileinput import close
from itertools import count

from Python.Foundation import contactNo
from numpy.testing import print_coercion_tables

print(type("usman"))



<class 'str'>


In [9]:
x=int(input("enter 1st number"))
y=int(input("enter 2nd number"))
x,y =y,x
print(f"before swap:{y,x} after swap {x,y}")

before swap:(4, 5) after swap (5, 4)


In [11]:
uniName= "VU"
colour = "blue"
height= 6
print(uniName,colour,height)

VU blue 6


In [14]:
name = input("enter name")
age = int(input("enter age"))
gender= input("enter gender")
contactNo= int(input("enter contact number"))
print(f"Your name is:{name}\n Age:{age} gender:{gender}contactNo:{contactNo}")

Your name is:Usman
 Age:33 gender:MalecontactNo:344


In [4]:
student = {"name":"Usman","age":22,"gender":"M","contactNo":123}
print(student["name"])
student["age"]=23
print(student["age"])

Usman
23


In [1]:
import numpy as np
import pandas as pd

In [4]:
thislist= list((1,2,3,4,5,6,7,8,9,10,11,12,13,14,15))
print(thislist)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [87]:
thislist = ["apple", "banana", "cherry"]
if "apple" in thislist:
  print("Yes, 'apple' is in the fruits list")

Yes, 'apple' is in the fruits list


In [92]:
thislist[1] = "Mango"
print(thislist)

['apple', 'Mango', 'water', 'cherry']


In [93]:
thislist[1:3] = ["blackcurrant", "water"]
print(thislist)

['apple', 'blackcurrant', 'water', 'cherry']


In [94]:
thislist[1:2] = ["blueberry", "wat"]
print(thislist)

['apple', 'blueberry', 'wat', 'water', 'cherry']


In [95]:
list1 = ["apple", "banana", "cherry"]
list1[1:3] = ["blackcurrant"]
print(list1)

['apple', 'blackcurrant']


In [97]:
thislist = ["apple", "banana", "cherry"]
thislist.insert(2, "watermelon")
print(thislist)

['apple', 'banana', 'watermelon', 'cherry']


In [98]:
list3 = ["apple", "banana", "cherry"]
list3.append("alo")
print(list3)

['apple', 'banana', 'cherry', 'alo']


In [108]:
list4 =["mango", "banana", "cherry"]
list5 = ["apple", "banana", "cherry"]
list4.extend(list5)
print(list4)

['mango', 'banana', 'cherry', 'apple', 'banana', 'cherry']


In [109]:
thistuple = (9,4,4,4)
list5.extend(thistuple)
print(list5)

['apple', 'banana', 'cherry', 9, 4, 4, 4]


In [110]:
list5.remove(9)
print(list5)

['apple', 'banana', 'cherry', 4, 4, 4]


In [111]:
list4.pop(1)
print(list4)

['mango', 'cherry', 'apple', 'banana', 'cherry']


In [113]:
list6 = [1,2,3,4,5,6,7,8,"p"]
list6.pop(5)
print(list6)

[1, 2, 3, 4, 5, 7, 8, 'p']


In [114]:
del list6[2]
print(list6)

[1, 2, 4, 5, 7, 8, 'p']


In [118]:
list7 =[12,223,3,44,45,6]
del list7


In [119]:
list8 = [1,23,46]
list8.clear()
print(list8)

[]


In [64]:
for x in list6:
  print(x)

1
2
4
5
6
7
8
p


In [122]:
thislist = ["apple", "banana", "cherry",1,4,6]
for i in range(len(thislist)):
  print(thislist[i])

apple
banana
cherry
1
4
6


In [123]:
thislist = ["apple", "banana", "cherry"]
i = 0
while i < len(thislist):
  print(thislist[i])
  i = i + 1


apple
banana
cherry


In [124]:
namelist= ["Usman","Ashfaq","Azan"]
i=0
while i < len(namelist):
    print(namelist[i])
    i = i + 1

Usman
Ashfaq
Azan


In [125]:
[print(x) for x in namelist]

Usman
Ashfaq
Azan


[None, None, None]

In [130]:
fruits = ['apple', 'banana', 'cherry']
newlist = [x for x in fruits if x == 'banana']
print(newlist)
print(fruits[1])

['banana']
banana


In [131]:
fruits = ['apple', 'banana', 'cherry']
newlist = ['apple' for x in fruits]
print(newlist)

['apple', 'apple', 'apple']


In [132]:

fruits = ['apple', 'banana', 'cherry']
newlist = [x for x in fruits if x != 'banana']
print(newlist)
newlist1 =[x.upper() for x in fruits]
print(newlist1)
newlist1 = ["hello" for x in fruits]
print(newlist1)


['apple', 'cherry']
['APPLE', 'BANANA', 'CHERRY']
['hello', 'hello', 'hello']


In [135]:
newlist1 = [x for x in range(10) if x<5]
print(newlist1)

[0, 1, 2, 3, 4]


In [136]:
fruits1 = ['apple', 'banana', 'cherry',"mango","appple"]
fruits1.sort()
print(fruits1)


['apple', 'appple', 'banana', 'cherry', 'mango']


In [137]:
numlist =[1,2,5,6,2,4,11,45,66,7,9,00]
numlist.sort()
print(numlist)

[0, 1, 2, 2, 4, 5, 6, 7, 9, 11, 45, 66]


In [138]:
numlist.sort(reverse=True)
print(numlist)

[66, 45, 11, 9, 7, 6, 5, 4, 2, 2, 1, 0]


In [139]:
newlist1 = numlist.copy()
print(newlist1)

[66, 45, 11, 9, 7, 6, 5, 4, 2, 2, 1, 0]


In [140]:
list= ["apple", "banana", "cherry"]
li= [1,2,3]
list= li
print(list)

[1, 2, 3]


In [141]:
lista= ["apple", "banana", "cherry"]
listb = lista
print(listb)

['apple', 'banana', 'cherry']


In [142]:
listnew2 = list6+lista
print(listnew2)

[1, 2, 4, 5, 7, 8, 'p', 'apple', 'banana', 'cherry']


In [101]:
list1 = ["a", "b" , "c"]
list2 = [1, 2, 3]

for x in list2:
  list1.append(x)

print(list1)


['a', 'b', 'c', 1, 2, 3]


In [103]:
list1.extend(list2)
print(list1)

['a', 'b', 'c', 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [143]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

In [105]:
thisdict

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

In [106]:
print(thisdict["brand"])

Ford


In [107]:
len(thisdict)

3

In [108]:
type(thisdict)

dict

In [109]:
type(thisdict["brand"])

str

In [110]:
dict1= dict(name = "Usman", age = 20, gender = "M")
dict1

{'name': 'Usman', 'age': 20, 'gender': 'M'}

In [111]:
x = {"name":"Usman", "age":20, "gender":"M"}
print(len(x))

3


In [139]:
x = thisdict.get("brand")
print(x)

Ford


In [116]:
x = thisdict.keys()
print(x)

dict_keys(['brand', 'model', 'year'])


In [120]:
x =thisdict.values()
print(x)

dict_values(['Ford', 'Mustang', 1964])


In [144]:
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}

x = car.keys()

print(x) #before the change

car["color"] = "white"

print(x) #after the change


dict_keys(['brand', 'model', 'year'])
dict_keys(['brand', 'model', 'year', 'color'])


In [145]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
x = thisdict.keys()
thisdict["colour"] = "red"
print(x)
x = thisdict.values()
print(x)

dict_keys(['brand', 'model', 'year', 'colour'])
dict_values(['Ford', 'Mustang', 1964, 'red'])


In [142]:
x = thisdict.items()
print(x)

dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964), ('colour', 'red')])


In [146]:
if "model" in thisdict:
    print("yes, model is one of the keys in the dictionary")

yes, model is one of the keys in the dictionary


In [150]:
thisdict["model"] = "2018"
print(thisdict)

{'brand': 'Ford', 'year': 1964, 'colour': 'red', 'color': 'red', 'model': '2018'}


In [151]:
thisdict.update({"model": "Mustang"})
print(thisdict)

{'brand': 'Ford', 'year': 1964, 'colour': 'red', 'color': 'red', 'model': 'Mustang'}


In [152]:
thisdict["color"] = "red"
print(thisdict)

{'brand': 'Ford', 'year': 1964, 'colour': 'red', 'color': 'red', 'model': 'Mustang'}


In [153]:
thisdict.pop("model")
print(thisdict)

{'brand': 'Ford', 'year': 1964, 'colour': 'red', 'color': 'red'}


In [148]:
thisdict.popitem()
print(thisdict)

{'brand': 'Ford', 'year': 1964, 'colour': 'red'}


In [154]:
del thisdict["year"]
print(thisdict)

{'brand': 'Ford', 'colour': 'red', 'color': 'red'}


In [155]:
dict1= {"keys":"values"}
dict1

{'keys': 'values'}

In [156]:
dict1.clear()
print(dict1)

{}


In [157]:
for i in thisdict:
    print(i)

brand
colour
color


In [158]:
for i in thisdict:
    print(thisdict[i])

Ford
red
red


In [159]:
for i in thisdict.values():
    print(i)

Ford
red
red


In [160]:
for i in thisdict.keys():
    print(i)

brand
colour
color


In [161]:
for i in thisdict.items():
    print(i)

('brand', 'Ford')
('colour', 'red')
('color', 'red')


In [162]:
mydict = thisdict.copy()
print(mydict)

{'brand': 'Ford', 'colour': 'red', 'color': 'red'}


In [163]:
mydict= dict(thisdict)
print(mydict)

{'brand': 'Ford', 'colour': 'red', 'color': 'red'}


In [164]:
myfamily = {
  "child1" : {
    "name" : "Emil",
    "year" : 2004
  },
  "child2" : {
    "name" : "Tobias",
    "year" : 2007
  },
  "child3" : {
    "name" : "Linus",
    "year" : 2011
  }
}

In [165]:
myfamily

{'child1': {'name': 'Emil', 'year': 2004},
 'child2': {'name': 'Tobias', 'year': 2007},
 'child3': {'name': 'Linus', 'year': 2011}}

In [166]:
child1 = {
  "name" : "Emil",
  "year" : 2004
}
child2 = {
  "name" : "Tobias",
  "year" : 2007
}
child3 = {
  "name" : "Linus",
  "year" : 2011
}

myfamily = {
  "child1" : child1,
  "child2" : child2,
  "child3" : child3
}

In [167]:
myfamily

{'child1': {'name': 'Emil', 'year': 2004},
 'child2': {'name': 'Tobias', 'year': 2007},
 'child3': {'name': 'Linus', 'year': 2011}}

In [168]:
print(myfamily["child2"]["name"])
print(myfamily["child3"]["name"])
print(myfamily["child3"]["year"])

Tobias
Linus
2011


In [169]:
for x, obj in myfamily.items():
  print(x)

  for y in obj:
    print(y + ':', obj[y])

child1
name: Emil
year: 2004
child2
name: Tobias
year: 2007
child3
name: Linus
year: 2011


In [175]:
import pandas as pd
que = pd.read_csv("Questions.csv")
randomquestions = que.sample(5)
# print(randomquestions)
questions = list(dict(randomquestions)["Question"])
optionAs = list(dict(randomquestions)["Option A"])
optionBs = list(dict(randomquestions)["Option B"])
optionCs =  list(dict(randomquestions)["Option C"])
optionDs =   list(dict(randomquestions)["Option D"])
rightAnswers = list(dict(randomquestions)["Right Answer"])
name = input("Enter your name: ")
for i in range(0,5):
  print("===========//==========")
  print(f" Questions: {questions[i]} Option A: {optionAs[i]} Option B {optionBs[i]} Option C {optionCs[i]} Option D {optionDs[i]} Right Answers {rightAnswers[i]}")




TypeError: 'list' object is not callable

In [176]:
import numpy as np

print(np.__version__)


2.5.1


In [179]:
arr =np.array((1,2,3,4,5,6,7,8))
print(arr)
print(type(arr))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [180]:
arr1 = np.array(43)
print(arr1)

43


In [196]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [197]:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [198]:
arr2 = [1,2,3,4,4]
arr2[0]
print(arr2[0]+arr2[2])

4


In [199]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [200]:

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [212]:
arr1 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print( "third element of 4th row: ",arr1[1, 1, 2])
print( "last element of 4th row: ",arr1[1, 1, -1])
print( "last element of 3rd row: ",arr1[1, 0, -1])
print( "last element of 1st row: ",arr1[0, 1, -1])
print( "last element of 0th row: ",arr1[0, 0, -1])

third element of 4th row:  12
last element of 4th row:  12
last element of 3rd row:  9
last element of 1st row:  6
last element of 0th row:  3


In [213]:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [220]:
arr2 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr2[1:5])
print(arr2[1:5:2])

[2 3 4 5]
[2 4]


In [221]:
arr2[5:]

arr2[:5]

array([1, 2, 3, 4, 5])

In [222]:
arr2[::2]

array([1, 3, 5, 7])

In [224]:
arr2[2:]

array([3, 4, 5, 6, 7])

In [227]:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0, 1])

2


In [233]:
arr[1,0:3]

array([6, 7, 8])

In [232]:
arr[0:2,3]

array([4, 9])

In [259]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:3])

[[2 3]
 [7 8]]


In [240]:
# Data  types in numpy
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr*2)
print(arr.dtype)

[2 4 6 8]
int64


In [261]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [235]:
arr = np.array([1, 2, 3, 4], dtype='f')

print(arr)
print(arr.dtype)

[1. 2. 3. 4.]
float32


In [236]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [241]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [273]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [275]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)


[ True False  True]


In [279]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[1] = 42

print(arr)
print(x)

[ 1 42  3  4  5]
[1 2 3 4 5]


In [280]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)


[31  2  3  4  5]
[31  2  3  4  5]


In [305]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1])
x = arr.copy()
y = arr.view()
print(x)
print(y)
print(x.base)
print(y.base)

2
[1 2 3 4 5]
[1 2 3 4 5]
None
[1 2 3 4 5]


In [322]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
print(arr[1,:3])

(2, 4)
[[5 6 7]]


In [244]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]] , ndmin=5)
print(arr)
print("Shape of the array: ",arr.shape)

[[[[[1 2 3 4]
    [5 6 7 8]]]]]
Shape of the array:  (1, 1, 1, 2, 4)


In [254]:
print(arr[0,0,0,0,3])
print(arr[0,0,0,1,3])
print(arr[0,0,0,0])
print(arr[0,0,0,1])
print(arr[0,0,0,0:1])

4
8
[1 2 3 4]
[5 6 7 8]
[[1 2 3 4]]


In [256]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)
print(newarr[2,0])
print(newarr[1,0])
print(newarr[3,1])
print(newarr[0,1])
print(newarr[2,0])


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
7
4
11
2
7


In [258]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)
print(newarr[0,0,0])
print(newarr[0,1,0])
print(newarr[0,2,0])
print(newarr[1,2,0])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
1
3
5
11


In [259]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4))

[[1 2 3 4]
 [5 6 7 8]]


In [355]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
arr[0,0,0,0,3]

[[[[[1 2 3 4]]]]]


np.int64(4)

In [266]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2,2, -1)

print(newarr)
print(newarr[0,0,0])


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1


In [383]:
arr = np.array([[[1, 2, 3], [4, 5, 6]]])

newarr = arr.reshape(-1)

print(newarr)


[1 2 3 4 5 6]


In [384]:
arr = np.array([1,2,2,3,33,4,4])
for x in arr:
    print(x)

1
2
2
3
33
4
4


In [271]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [388]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [389]:
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [390]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [275]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[1:, ::2]):
  print(x)

5
7


In [399]:
arr = np.array([1, 2, 3,4,5,6])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6


In [400]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [277]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
for x in np.nditer(arr[::2]):
  print(x)

1
3
5
7


In [411]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)



[1 2 3 4 5 6]


In [281]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2),axis=1)

print(arr)
print(arr[0,1])

[[1 2 5 6]
 [3 4 7 8]]
2


In [427]:
arr1 = np.array([1, 2, 3,2])

arr2 = np.array([4, 5, 6,2])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]
 [2 2]]


In [420]:
, axis=arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [428]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


In [429]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [442]:
car = {"brand":"Ford","model":"Mustang","year":"2012"}
car["model"] = "Kia"
car["color"] = "red"
car["type"] ="new"
car

{'brand': 'Ford',
 'model': 'Kia',
 'year': '2012',
 'color': 'red',
 'type': 'new'}

In [438]:
car.pop("brand")

'Ford'

In [439]:
car

{'model': 'Kia', 'year': '2012', 'color': 'red'}

In [443]:
import  pandas as pd


In [451]:
file = open("file.txt","w")
file = open("file.txt","r")

In [457]:
file = open("file.txt","r")
print(file.read())
file.close()

Ali
Ahmed
Usman
Sara
Ali
Ahmed
Usman
Sara


In [460]:
with open("file.txt","r") as f:
    print(f.read())

Ali
Ahmed
Usman
Sara
Ali
Ahmed
Usman
Sara


In [462]:
with open("file.txt","r") as f:
    print(f.readline())

Ali



In [467]:
with open("file.txt","r") as f:
    print(f.readlines())


['Ali\n', 'Ahmed\n', 'Usman\n', 'Sara\n', 'Ali\n', 'Ahmed\n', 'Usman\n', 'Sara']


In [478]:
with open("file.txt", "r") as f:

    for line in f:
        print(line)

Ali

Ahmed

Usman

Sara

Ali

Ahmed

Usman

Sara


In [479]:
with open("file.txt", "r") as f:

    for line in f:
        print(line.strip())

Ali
Ahmed
Usman
Sara
Ali
Ahmed
Usman
Sara


In [5]:
newfile = open("newfile.txt","r")
print(newfile.read())
with open("myfile.txt", "w") as file:
    file.write("Usman\n")
    file.write("Ashfaq\n")
    file.write("Azan\n")
with open("myfile.txt", "a") as file:
    file.write("Salam\n")


In [7]:
with open("newfile2.txt", "x") as file:
    file.write("Usman\n")


In [9]:
import os

if os.path.exists("newfile.txt"):
    print("File exists")
else:
    print("File not found")

File exists


In [12]:
if os.path.exists(("newfile2.txt")):
    print("file exists")
else:
    print("file not found")

file exists


In [13]:
os.remove("newfile2.txt")

In [18]:
import os

if os.path.exists("myfile.txt"):
    os.remove("myfile.txt")
else:
    print("File not found")

In [22]:
name = input("Enter your name: ")
with open("myfile2.txt", "a") as file:
    file.write(name+"\n")
print("Name saved Successfully")

Name saved Successfully


In [21]:
""""""Practice Exercises

Try these on your own:

Create a file named marks.txt.
Write the marks of five students.
Read and print all marks.
Add one more student's marks using append mode.
Count how many lines are in the file.
Search for a student's name in the file.
Copy the contents of one file into another file.
Delete a file only if it exists.
""""""

In [41]:

with open("marks.txt", "w") as file:
    file.write("Usman")
    print("Marks File created successfully")


Marks File created successfully


In [72]:
with open("marks.txt", "w") as file:
    file.write("Usman, 30\n")
    file.write("Ashfaq,40\n")
    file.write("Azan,500\n")
    file.write("Salman,60\n")
    file.write("Usama,70\n")
print("Students marks added successfully")


Students marks added successfully


In [71]:
with open("marks.txt", "r") as file:
    print(file.read())

Usman, 30
Ashfaq,40
Azan,500
Salman,60
Usama,70
Umer.80



In [73]:
with open("marks.txt", "a") as file:
    file.write("Umer.80\n")
    print("New student added successfully")

New student added successfully


In [74]:
with open("marks.txt", "r") as file:
    lines= file.readlines()
    print("Total Student: ", len(lines))


Total Student:  6


In [75]:
count = 0
with open("marks.txt", "r") as file:
    for i in file:
        count +=1
print("Total Student: ",count)

Total Student:  6


In [287]:
name= input("enter student name:")
found = True
with open("marks.txt", "r") as file:
    for line in file:
        if name.lower() in line.lower():
            print("Record found")
            print(line)
            found = True
            break
if not found:
    print("Record not found")

In [76]:
highest = 0
student = ""

with open("marks.txt", "r") as file:
    for line in file:
        name, marks = line.strip().split(",")
        marks = int(marks)

        if marks > highest:
            highest = marks
            student = name

print("Top Student:", student)
print("Highest Marks:", highest)

ValueError: not enough values to unpack (expected 2, got 1)

In [61]:
total = 0
count = 0

with open("marks.txt", "r") as file:
    for line in file:
        name, marks = line.strip().split(",")
        total += int(marks)
        count += 1

average = total / count

print("Average Marks:", average)

ValueError: not enough values to unpack (expected 2, got 1)

In [78]:
count = 0
with open("marks.txt","r") as file:
    for i in file:
        count += 1
print("Total students in the file: ",count)

Total students in the file:  6


In [80]:
with open("marks.txt","r") as file:
    lines = file.readlines()
    print("Total students in the file: ", len(lines))

Total students in the file:  6


In [170]:
import pandas as pd

marks = pd.Series([85, 90, 78, 95])

print(marks)

0    85
1    90
2    78
3    95
dtype: int64


In [171]:
import pandas as pd

marks = pd.Series([85, 90, 78])

print(marks[0])
print(marks[2])

85
78


In [291]:
import pandas as pd

marks = pd.Series(
    [85, 90, 78],
    index=["Ali", "Ahmed", "Sara"]
)

print(marks)

Ali      85
Ahmed    90
Sara     78
dtype: int64


In [177]:
print(marks["Ali"])

85


In [ ]:
import pandas as pd

data = {
    "Name": ["Ali", "Ahmed", "Sara"],
    "Age": [20, 21, 22],
    "Marks": [85, 92, 88]
}
print(data)
df = pd.DataFrame(data)

print(df)

In [182]:
print(df.head(1))

  Name  Age  Marks
0  Ali   20     85


In [187]:
print(df.tail(1))

   Name  Age  Marks
2  Sara   22     88


In [188]:
print(df.shape)

(3, 3)


In [189]:
print(df.columns)

Index(['Name', 'Age', 'Marks'], dtype='str')


In [190]:
print(df.dtypes)

Name       str
Age      int64
Marks    int64
dtype: object


In [191]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      str  
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), str(1)
memory usage: 204.0 bytes
None


In [193]:
print(df.describe())

        Age      Marks
count   3.0   3.000000
mean   21.0  88.333333
std     1.0   3.511885
min    20.0  85.000000
25%    20.5  86.500000
50%    21.0  88.000000
75%    21.5  90.000000
max    22.0  92.000000


In [303]:
import pandas as pd
df = pd.read_csv("family.csv")

In [305]:
print(df)

   Unnamed: 0   fName   lName  age  Class gender
0           0   Usman  Ashfaq   21    0ne   male
1           1  Salman  Ashfaq   22    two   male
2           2    Amir  Ashfaq   23  three   male
3           3    Umer  Ashfaq   24   four   male
4           4   Irfan  Ashfaq   25   five   male


In [309]:
print(df[["fName","lName","age","Class","gender"]])

    fName   lName  age  Class gender
0   Usman  Ashfaq   21    0ne   male
1  Salman  Ashfaq   22    two   male
2    Amir  Ashfaq   23  three   male
3    Umer  Ashfaq   24   four   male
4   Irfan  Ashfaq   25   five   male


In [312]:
print(df.iloc[3])

Unnamed: 0         3
fName           Umer
lName         Ashfaq
age               24
Class           four
gender          male
Name: 3, dtype: object


In [313]:
import pandas as pd

students = {
    "Name": ["Ali", "Ahmed", "Sara", "Usman"],
    "Age": [20, 21, 22, 23],
    "Marks": [85, 90, 95, 80]
}

df = pd.DataFrame(students)

In [314]:
print(df)

    Name  Age  Marks
0    Ali   20     85
1  Ahmed   21     90
2   Sara   22     95
3  Usman   23     80


In [318]:
print(df["Name"])


0      Ali
1    Ahmed
2     Sara
3    Usman
Name: Name, dtype: str


In [317]:
print(df["Marks"])

0    85
1    90
2    95
3    80
Name: Marks, dtype: int64


In [320]:
print(df.head(2))

    Name  Age  Marks
0    Ali   20     85
1  Ahmed   21     90


In [321]:
print(df.tail(2))

    Name  Age  Marks
2   Sara   22     95
3  Usman   23     80


In [322]:
print(df.shape)

(4, 3)


In [323]:
print(df.columns)

Index(['Name', 'Age', 'Marks'], dtype='str')


In [324]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      str  
 1   Age     4 non-null      int64
 2   Marks   4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes
None


In [325]:
print(df.dtypes)

Name       str
Age      int64
Marks    int64
dtype: object


In [326]:
print(df.describe())

             Age      Marks
count   4.000000   4.000000
mean   21.500000  87.500000
std     1.290994   6.454972
min    20.000000  80.000000
25%    20.750000  83.750000
50%    21.500000  87.500000
75%    22.250000  91.250000
max    23.000000  95.000000


In [327]:
print(df[["Name","Marks"]])

    Name  Marks
0    Ali     85
1  Ahmed     90
2   Sara     95
3  Usman     80


In [333]:

df = pd.read_csv("bank.csv")

bankingSys = {"name":["Usman"],
              "ATMpin":[1234],"bal":[]}
name = input("enter your name:")
ATMpin = input(int("enter your ATMpin:"))
for i in bankingSys.values():
    if ATMpin in bankingSys["ATMpin"]:
      print("Access allowed you can Deposit/withdraw/check balance ")
      choice = input("Enter 1 to Deposit, 2 to withdraw, 3 to check balance")
      choice = input(int("Enter Amount"))
      if choice == 1:


In [334]:
# BANK SYSTEM — DO NOT MODIFY
# Read bank CSV into dictionary for in-memory manipulation
df = pd.read_csv("bank.csv")
bank = {}
for i in range(len(df)):
    account = str(df["AccountNumber"][i])
    bank[account] = {
        "FName": df["FName"][i],
        "LName": df["LName"][i],
        "Password": str(df["Password"][i]),
        "Address": df["Address"][i],
        "Class": df["Class"][i],
        "City": df["City"][i],
        "Balance": float(df["Balance"][i])
    }
while True:
    print("\n1. Create Account")
    print("2. Login")
    print("3. Exit")
    choice = input("Enter Choice: ")
    if choice == "1":
        account = input("Account Number: ")
        if account in bank:
            print("Account Already Exists")
        else:
            bank[account] = {}
            bank[account]["FName"] = input("First Name: ")
            bank[account]["LName"] = input("Last Name: ")
            bank[account]["Password"] = input("Password: ")
            bank[account]["Address"] = input("Address: ")
            bank[account]["Class"] = input("Class: ")
            bank[account]["City"] = input("City: ")
            bank[account]["Balance"] = float(input("Opening Balance: "))
            print("Account Created")

    elif choice == "2":
        account = input("Account Number: ")
        password = input("Password: ")
        if account in bank and password == bank[account]["Password"]:
            while True:
                print("\n1. View Details")
                print("2. Check Balance")
                print("3. Deposit")
                print("4. Withdraw")
                print("5. Logout")
                option = input("Choice: ")
                if option == "1":
                    print("First Name :", bank[account]["FName"])
                    print("Last Name :", bank[account]["LName"])
                    print("Address :", bank[account]["Address"])
                    print("Class :", bank[account]["Class"])
                    print("City :", bank[account]["City"])
                    print("Balance :", bank[account]["Balance"])
                elif option == "2":
                    print("Balance :", bank[account]["Balance"])
                elif option == "3":
                    amount = float(input("Amount: "))
                    bank[account]["Balance"] = bank[account]["Balance"] + amount
                    print("New Balance :", bank[account]["Balance"])
                elif option == "4":
                    amount = float(input("Amount: "))
                    if amount <= bank[account]["Balance"]:
                        bank[account]["Balance"] = bank[account]["Balance"] - amount
                        print("Remaining Balance :", bank[account]["Balance"])
                    else:
                        print("Insufficient Balance")
                elif option == "5":
                    break
                else:
                    print("Invalid Choice")
        else:
            print("Invalid Account or Password")
    elif choice == "3":
        accounts = []
        fname = []
        lname = []
        password = []
        address = []
        student_class = []
        city = []
        balance = []
        for account in bank:
            accounts.append(account)
            fname.append(bank[account]["FName"])
            lname.append(bank[account]["LName"])
            password.append(bank[account]["Password"])
            address.append(bank[account]["Address"])
            student_class.append(bank[account]["Class"])
            city.append(bank[account]["City"])
            balance.append(bank[account]["Balance"])
        df = pd.DataFrame({
            "AccountNumber": accounts,
            "FName": fname,
            "LName": lname,
            "Password": password,
            "Address": address,
            "Class": student_class,
            "City": city,
            "Balance": balance
        })
        df.to_csv("bank.csv", index=False)
        print("Data Saved")
        break
    else:
        print("Invalid Choice")

FileNotFoundError: [Errno 2] No such file or directory: 'bank.csv'

In [ ]:
from app import server
