In [4]:
from Python.Foundation import contactNo
from numpy.testing import print_coercion_tables

print(type("usman"))



<class 'str'>


In [9]:
x=int(input("enter 1st number"))
y=int(input("enter 2nd number"))
x,y =y,x
print(f"before swap:{y,x} after swap {x,y}")

before swap:(4, 5) after swap (5, 4)


In [11]:
uniName= "VU"
colour = "blue"
height= 6
print(uniName,colour,height)

VU blue 6


In [14]:
name = input("enter name")
age = int(input("enter age"))
gender= input("enter gender")
contactNo= int(input("enter contact number"))
print(f"Your name is:{name}\n Age:{age} gender:{gender}contactNo:{contactNo}")

Your name is:Usman
 Age:33 gender:MalecontactNo:344


In [4]:
student = {"name":"Usman","age":22,"gender":"M","contactNo":123}
print(student["name"])
student["age"]=23
print(student["age"])

Usman
23


In [1]:
import numpy as np
import pandas as pd

In [4]:
thislist= list((1,2,3,4,5,6,7,8,9,10,11,12,13,14,15))
print(thislist)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]


In [5]:
thislist = ["apple", "banana", "cherry"]
if "apple" in thislist:
  print("Yes, 'apple' is in the fruits list")

Yes, 'apple' is in the fruits list


In [6]:
thislist[1] = "Mango"
print(thislist)

['apple', 'Mango', 'cherry']


In [12]:
thislist[1:3] = ["blackcurrant", "water"]
print(thislist)

['apple', 'blackcurrant', 'water', 'watermelon']


In [14]:
thislist[1:2] = ["blueberry", "wat"]
print(thislist)

['apple', 'blueberry', 'wat', 'water', 'water', 'watermelon']


In [17]:
list1 = ["apple", "banana", "cherry"]
list1[1:3] = ["blackcurrant"]
print(list1)

['apple', 'blackcurrant']


In [23]:
thislist = ["apple", "banana", "cherry"]
thislist.insert(3, "watermelon")
print(thislist)

['apple', 'banana', 'cherry', 'watermelon']


In [26]:
list3 = ["apple", "banana", "cherry"]
list3.append("alo")
print(list3)

['apple', 'banana', 'cherry', 'alo']


In [38]:
list4 =["mango", "banana", "cherry"]
list5 = ["apple", "banana", "cherry"]
list4.extend(list5)
print(list4)

['mango', 'banana', 'cherry', 'apple', 'banana', 'cherry']


In [39]:
thistuple = (9,4,4,4)
list5.extend(thistuple)
print(list5)

['apple', 'banana', 'cherry', 9, 4, 4, 4]


In [40]:
list5.remove(4)
print(list5)

['apple', 'banana', 'cherry', 9, 4, 4]


In [44]:
list4.pop(1)
print(list4)

['mango', 'cherry', 'apple', 'banana', 'cherry']


In [63]:
list6 = [1,2,3,4,5,6,7,8,"p"]
list6.pop(2)
print(list6)

[1, 2, 4, 5, 6, 7, 8, 'p']


In [56]:
del list6[2]
print(list6)

[1, 2, 5, 6, 7, 8]


In [57]:
list7 =[12,223,3,44,45,6]
del list7

In [59]:
list8 = [1,23,46]
list8.clear()
print(list8)

[]


In [64]:
for x in list6:
  print(x)

1
2
4
5
6
7
8
p


In [62]:
thislist = ["apple", "banana", "cherry",1,4,6]
for i in range(len(thislist)):
  print(thislist[i])

apple
banana
cherry
1
4
6


In [65]:
thislist = ["apple", "banana", "cherry"]
i = 0
while i < len(thislist):
  print(thislist[i])
  i = i + 1


apple
banana
cherry


In [66]:
namelist= ["Usman","Ashfaq","Azan"]
i=0
while i < len(namelist):
    print(namelist[i])
    i = i + 1

Usman
Ashfaq
Azan


In [68]:
[print(x) for x in namelist]

Usman
Ashfaq
Azan


[None, None, None]

In [74]:
fruits = ['apple', 'banana', 'cherry']
newlist = [x for x in fruits if x == 'banana']
print(newlist)

['banana']


In [75]:
ruits = ['apple', 'banana', 'cherry']
newlist = ['apple' for x in fruits]
print(newlist)

['apple', 'apple', 'apple']


In [87]:

fruits = ['apple', 'banana', 'cherry']
newlist = [x for x in fruits if x != 'banana']
print(newlist)
newlist1 =[x.upper() for x in fruits]
print(newlist1)
newlist1 = ["hello" for x in fruits]
print(newlist1)


['apple', 'cherry']
['APPLE', 'BANANA', 'CHERRY']
['hello', 'hello', 'hello']


In [80]:
newlist1 = [x for x in range(10) if x<5]
print(newlist1)

[0, 1, 2, 3, 4]


In [90]:
fruits1 = ['apple', 'banana', 'cherry',"mango","appple"]
fruits1.sort()
print(fruits1)


['apple', 'appple', 'banana', 'cherry', 'mango']


In [91]:
numlist =[1,2,5,6,2,4,11,45,66,7,9,00]
numlist.sort()
print(numlist)

[0, 1, 2, 2, 4, 5, 6, 7, 9, 11, 45, 66]


In [92]:
numlist.sort(reverse=True)
print(numlist)

[66, 45, 11, 9, 7, 6, 5, 4, 2, 2, 1, 0]


In [93]:
newlist1 = numlist.copy()
print(newlist1)

[66, 45, 11, 9, 7, 6, 5, 4, 2, 2, 1, 0]


In [95]:
list= ["apple", "banana", "cherry"]
li= [1,2,3]
list= li
print(list)

[1, 2, 3]


In [97]:
lista= ["apple", "banana", "cherry"]
listb = lista[:]
print(listb)

['apple', 'banana', 'cherry']


In [100]:
listnew2 = list6+lista
print(listnew2)

[1, 2, 4, 5, 6, 7, 8, 'p', 'apple', 'banana', 'cherry']


In [101]:
list1 = ["a", "b" , "c"]
list2 = [1, 2, 3]

for x in list2:
  list1.append(x)

print(list1)


['a', 'b', 'c', 1, 2, 3]


In [103]:
list1.extend(list2)
print(list1)

['a', 'b', 'c', 1, 2, 3, 1, 2, 3, 1, 2, 3]


In [138]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}

In [105]:
thisdict

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}

In [106]:
print(thisdict["brand"])

Ford


In [107]:
len(thisdict)

3

In [108]:
type(thisdict)

dict

In [109]:
type(thisdict["brand"])

str

In [110]:
dict1= dict(name = "Usman", age = 20, gender = "M")
dict1

{'name': 'Usman', 'age': 20, 'gender': 'M'}

In [111]:
x = {"name":"Usman", "age":20, "gender":"M"}
print(len(x))

3


In [139]:
x = thisdict.get("brand")
print(x)

Ford


In [116]:
x = thisdict.keys()
print(x)

dict_keys(['brand', 'model', 'year'])


In [120]:
x =thisdict.values()
print(x)

dict_values(['Ford', 'Mustang', 1964])


In [140]:
car = {
"brand": "Ford",
"model": "Mustang",
"year": 1964
}

x = car.keys()

print(x) #before the change

car["color"] = "white"

print(x) #after the change


dict_keys(['brand', 'model', 'year'])
dict_keys(['brand', 'model', 'year', 'color'])


In [141]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
x = thisdict.keys()
thisdict["colour"] = "red"
print(x)
x = thisdict.values()
print(x)

dict_keys(['brand', 'model', 'year', 'colour'])
dict_values(['Ford', 'Mustang', 1964, 'red'])


In [142]:
x = thisdict.items()
print(x)

dict_items([('brand', 'Ford'), ('model', 'Mustang'), ('year', 1964), ('colour', 'red')])


In [143]:
if "model" in thisdict:
    print("yes, model is one of the keys in the dictionary")

yes, model is one of the keys in the dictionary


In [144]:
thisdict["model"] = "2018"
print(thisdict)

{'brand': 'Ford', 'model': '2018', 'year': 1964, 'colour': 'red'}


In [145]:
thisdict.update({"model": "Mustang"})
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'colour': 'red'}


In [146]:
thisdict["color"] = "red"
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'colour': 'red', 'color': 'red'}


In [147]:
thisdict.pop("model")
print(thisdict)

{'brand': 'Ford', 'year': 1964, 'colour': 'red', 'color': 'red'}


In [148]:
thisdict.popitem()
print(thisdict)

{'brand': 'Ford', 'year': 1964, 'colour': 'red'}


In [149]:
del thisdict["year"]
print(thisdict)

{'brand': 'Ford', 'colour': 'red'}


In [150]:
dict1= {"keys":"values"}
dict1

{'keys': 'values'}

In [151]:
dict1.clear()
print(dict1)

{}


In [152]:
for i in thisdict:
    print(i)

brand
colour


In [153]:
for i in thisdict:
    print(thisdict[i])

Ford
red


In [154]:
for i in thisdict.values():
    print(i)

Ford
red


In [155]:
for i in thisdict.keys():
    print(i)

brand
colour


In [156]:
for i in thisdict.items():
    print(i)

('brand', 'Ford')
('colour', 'red')


In [157]:
mydict = thisdict.copy()
print(mydict)

{'brand': 'Ford', 'colour': 'red'}


In [158]:
mydict= dict(thisdict)
print(mydict)

{'brand': 'Ford', 'colour': 'red'}


In [159]:
myfamily = {
  "child1" : {
    "name" : "Emil",
    "year" : 2004
  },
  "child2" : {
    "name" : "Tobias",
    "year" : 2007
  },
  "child3" : {
    "name" : "Linus",
    "year" : 2011
  }
}

In [160]:
myfamily

{'child1': {'name': 'Emil', 'year': 2004},
 'child2': {'name': 'Tobias', 'year': 2007},
 'child3': {'name': 'Linus', 'year': 2011}}

In [161]:
child1 = {
  "name" : "Emil",
  "year" : 2004
}
child2 = {
  "name" : "Tobias",
  "year" : 2007
}
child3 = {
  "name" : "Linus",
  "year" : 2011
}

myfamily = {
  "child1" : child1,
  "child2" : child2,
  "child3" : child3
}

In [162]:
myfamily

{'child1': {'name': 'Emil', 'year': 2004},
 'child2': {'name': 'Tobias', 'year': 2007},
 'child3': {'name': 'Linus', 'year': 2011}}

In [165]:
print(myfamily["child2"]["name"])
print(myfamily["child3"]["name"])
print(myfamily["child3"]["year"])

Tobias
Linus
2011


In [167]:
for x, obj in myfamily.items():
  print(x)

  for y in obj:
    print(y + ':', obj[y])

child1
name: Emil
year: 2004
child2
name: Tobias
year: 2007
child3
name: Linus
year: 2011


In [175]:
import pandas as pd
que = pd.read_csv("Questions.csv")
randomquestions = que.sample(5)
# print(randomquestions)
questions = list(dict(randomquestions)["Question"])
optionAs = list(dict(randomquestions)["Option A"])
optionBs = list(dict(randomquestions)["Option B"])
optionCs =  list(dict(randomquestions)["Option C"])
optionDs =   list(dict(randomquestions)["Option D"])
rightAnswers = list(dict(randomquestions)["Right Answer"])
name = input("Enter your name: ")
for i in range(0,5):
  print("===========//==========")
  print(f" Questions: {questions[i]} Option A: {optionAs[i]} Option B {optionBs[i]} Option C {optionCs[i]} Option D {optionDs[i]} Right Answers {rightAnswers[i]}")




TypeError: 'list' object is not callable

In [176]:
import numpy as np

print(np.__version__)


2.5.1


In [179]:
arr =np.array((1,2,3,4,5,6,7,8))
print(arr)
print(type(arr))

[1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [180]:
arr1 = np.array(43)
print(arr1)

43


In [181]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [182]:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5


In [189]:
arr2 = [1,2,3,4,4]
arr2[0]
print(arr2[0]+arr2[2])

4


In [198]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [199]:

print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [208]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr[1, 1, 2])

12


In [209]:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [213]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[1:5:2])

[2 3 4 5]
[2 4]


In [229]:
arr[5:]

arr[:5]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [230]:
arr[::2]

array([[1, 2, 3, 4, 5]])

In [231]:
arr[2:]

array([], shape=(0, 5), dtype=int64)

In [232]:

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [233]:
arr[1,0:3]

array([6, 7, 8])

In [237]:
arr[0:2,4]

array([ 5, 10])

In [259]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 1:3])

[[2 3]
 [7 8]]


In [265]:
# Data  types in numpy
# i - integer
# b - boolean
# u - unsigned integer
# f - float
# c - complex float
# m - timedelta
# M - datetime
# O - object
# S - string
# U - unicode string
# V - fixed chunk of memory for other type ( void )

import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [261]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [262]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [266]:
import numpy as np

arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [272]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [273]:
arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)

[1 2 3]
int64


In [275]:
arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)


[ True False  True]


In [279]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[1] = 42

print(arr)
print(x)

[ 1 42  3  4  5]
[1 2 3 4 5]


In [280]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)


[31  2  3  4  5]
[31  2  3  4  5]


In [305]:
arr = np.array([1, 2, 3, 4, 5])
print(arr[1])
x = arr.copy()
y = arr.view()
print(x)
print(y)
print(x.base)
print(y.base)

2
[1 2 3 4 5]
[1 2 3 4 5]
None
[1 2 3 4 5]


In [322]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)
print(arr[1,:3])

(2, 4)
[[5 6 7]]


In [303]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]] , ndmin=5)
print(arr)
print("Shape of the array: ",arr.shape)

[[[[[1 2 3 4]
    [5 6 7 8]]]]]
Shape of the array:  (1, 1, 1, 2, 4)


In [298]:
print(arr[0,0,0,0])

[1 2 3 4]


In [338]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)
print(newarr[2,0])


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
7


In [347]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)
print(newarr[1,2,0])

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
11


In [348]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [355]:
arr = np.array([1, 2, 3, 4], ndmin=5)
print(arr)
arr[0,0,0,0,3]

[[[[[1 2 3 4]]]]]


np.int64(4)

In [366]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)
print(newarr[0,0,0])


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
1


In [383]:
arr = np.array([[[1, 2, 3], [4, 5, 6]]])

newarr = arr.reshape(-1)

print(newarr)


[1 2 3 4 5 6]


In [384]:
arr = np.array([1,2,2,3,33,4,4])
for x in arr:
    print(x)

1
2
2
3
33
4
4


In [387]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [388]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [389]:
for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


In [390]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [397]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [399]:
arr = np.array([1, 2, 3,4,5,6])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4
(4,) 5
(5,) 6


In [400]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [410]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
for x in np.nditer(arr[::2]):
  print(x)

1
3
5
7


In [411]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)



[1 2 3 4 5 6]


In [416]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)
print(arr[0,1])

[[1 2 5 6]
 [3 4 7 8]]
2


In [427]:
arr1 = np.array([1, 2, 3,2])

arr2 = np.array([4, 5, 6,2])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]
 [2 2]]


In [420]:
, axis=arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [428]:

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]
