# NumPy & Arrays

NumPy (Numerical Python) is the foundation of scientific computing in Python. It provides fast, memory-efficient N-dimensional arrays and powerful operations.

Key benefits over Python lists:
- Vectorized operations (no loops needed!)
- Faster computation (written in C)
- Rich library of mathematical functions


## Getting Started

Import NumPy with the standard alias `np`:


In [15]:
import numpy as np



In [14]:
arr = np.array([12,3,4,5],ndmin=2)

## Why NumPy? Performance Comparison

NumPy arrays are significantly faster than Python lists for numerical operations because they use compiled C code and contiguous memory.


In [15]:
import numpy as np



In [14]:
arr = np.array([12,3,4,5],ndmin=2)

In [ ]:
print(arr)
print(arr.ndim)
print(arr.shape)

[[12  3  4  5]]
2
(1, 4)


## Multi-dimensional Arrays & Reshaping

- `.reshape(rows, cols)` — change shape (total elements must match)
- `ndmin=N` — create with minimum N dimensions
- Use nested lists for 2D, 3D, 4D arrays


In [19]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr2 = np.array([[[1],[1]],[[1],[1]]])

In [33]:
print(arr2)
print(arr2.shape)
print("dimesnerions are: ,",arr2.ndim)

[[[1]
  [1]]

 [[1]
  [1]]]
(2, 2, 1)
dimesnerions are: , 3


In [7]:
arr =np.array([1,2,3,4])

In [8]:
arr

array([1, 2, 3, 4])

Numpy Again


In [5]:
import time
import numpy as np

# 1. Setup data size (10 million items)
DATA_SIZE = 10_000_000

# Initialize a standard Python list and a NumPy array
py_list = list(range(DATA_SIZE))
np_array = np.arange(DATA_SIZE)

print(f"Benchmarking operations over {DATA_SIZE:,} elements...\n")

# --- TEST 1: SUMMATION ---
# Measure Python list sum
start_time = time.time()
list_sum = sum(py_list)
list_sum_time = time.time() - start_time

# Measure NumPy array sum
start_time = time.time()
array_sum = np.sum(np_array)
array_sum_time = time.time() - start_time

print("### Test 1: Summing Elements ###")
print(f"Python List time: {list_sum_time:.5f} seconds")
print(f"NumPy Array time: {array_sum_time:.5f} seconds")
print(f"👉 NumPy is {list_sum_time / array_sum_time:.1f}x faster\n")


# --- TEST 2: ELEMENT-WISE MULTIPLICATION ---
# Measure Python list multiplication (requires a loop/list comprehension)
start_time = time.time()
list_mult = [x * 2 for x in py_list]
list_mult_time = time.time() - start_time

# Measure NumPy array multiplication (uses optimized vectorization)
start_time = time.time()
array_mult = np_array * 2
array_mult_time = time.time() - start_time

print("### Test 2: Multiplying Elements by 2 ###")
print(f"Python List time: {list_mult_time:.5f} seconds")
print(f"NumPy Array time: {array_mult_time:.5f} seconds")
print(f"👉 NumPy is {list_mult_time / array_mult_time:.1f}x faster\n")


Benchmarking operations over 10,000,000 elements...

### Test 1: Summing Elements ###
Python List time: 0.28637 seconds
NumPy Array time: 0.04044 seconds
👉 NumPy is 7.1x faster

### Test 2: Multiplying Elements by 2 ###
Python List time: 0.43839 seconds
NumPy Array time: 0.01956 seconds
👉 NumPy is 22.4x faster



## Creating NumPy Arrays

Create arrays from Python lists. NumPy also provides utility functions:
- `np.zeros(shape)` — array of zeros
- `np.ones(shape)` — array of ones
- `np.arange(start, stop, step)` — like `range()` but returns array
- `np.linspace(start, stop, n)` — n evenly spaced numbers
- `np.full(shape, value)` — array filled with a value


In [7]:
li = [1,2,3,4,5]
arr = np.array([1,2,3,4,5])

In [8]:
for i in li:
    print(i*2)

2
4
6
8
10


In [16]:
arr

array([1, 2, 3, 4, 5])

## Array Properties

- `.ndim` — number of dimensions
- `.shape` — tuple of dimensions (rows, cols, ...)
- `.size` — total number of elements
- `.dtype` — data type of elements


In [14]:
arr.ndim

1

In [ ]:
print("Size:", arr.size)     # total elements
print("Dtype:", arr.dtype)   # int32 or int64 etc.
print("itemsize:", arr.itemsize, "bytes")  # bytes per element


In [15]:
arr.shape

(5,)

In [ ]:
# Array creation utility functions
zeros_arr = np.zeros((3, 4))
print("Zeros:\n", zeros_arr)

ones_arr = np.ones((2, 3))
print("Ones:\n", ones_arr)

range_arr = np.arange(0, 20, 2)
print("Arange:", range_arr)  # [ 0  2  4  6  8 10 12 14 16 18]

linspace_arr = np.linspace(0, 1, 5)
print("Linspace:", linspace_arr)  # [0.   0.25 0.5  0.75 1.  ]


In [25]:
arr2D = np.array([1,2,3,4],ndmin=4)

In [26]:
print(arr2D)
print(arr2D.shape)

[[[[1 2 3 4]]]]
(1, 1, 1, 4)


In [28]:
arrMultiDimension = np.array([[1,2,3,4],[5,6,7,8]])

In [30]:
arrMultiDimension.shape

(2, 4)

In [34]:
arr3D =np.array([[[1,2,3,4],[5,6,7,8],[5,6,7,8]],[[1,2,3,4],[5,6,7,8],[5,6,7,8]]])

In [ ]:
arr3D
"""
array([[7, 8],
        [7, 8]],

        [7, 8],
        [7, 8]]])
"""

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8],
        [5, 6, 7, 8]]])

In [38]:
arr2D = np.array([[1,2,3,4],[5,6,7,8]])

In [39]:
arr2D

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

## Indexing & Slicing

Access array elements with indices and slices:
- 1D: `arr[start:end:step]`
- 2D: `arr[row_start:row_end, col_start:col_end]`
- 3D: `arr[depth_start:depth_end, row_start:row_end, col_start:col_end]`


In [51]:
arr2D[:,1:3]

array([[2, 3],
       [6, 7]])

In [56]:
arr3D =np.array([[[1,2,3,4],[5,6,7,8],[5,6,7,8]],[[1,2,3,4],[5,6,7,8],[5,6,7,8]]])
arr3D

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [5, 6, 7, 8]],

       [[1, 2, 3, 4],
        [5, 6, 7, 8],
        [5, 6, 7, 8]]])

In [55]:
arr3D[0:,1:,2:]

array([[[7, 8],
        [7, 8]],

       [[7, 8],
        [7, 8]]])

In [57]:
Arr = np.array(range(0,100))

In [58]:
Arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [61]:
evenList = []
oddList = []
for i in Arr:
    if i%2 == 0:
        evenList.append(i)
    else:
        oddList.append(i)

In [65]:
evenArray = np.array(evenList)
oddArrat = np.array(oddList)

In [67]:
evenArray
oddArrat

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

## Filtering & Boolean Indexing

Use boolean conditions to filter arrays. The condition returns a boolean mask.
```python
arr[arr > 50]  # all elements greater than 50
```


In [71]:
evenArray = Arr[Arr%2==0]
oddArray = Arr[Arr%2!=0]

In [73]:
print(evenArray)
print(oddArray)

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [76]:
evenArray[1]=5 

## Array Operations & Broadcasting

NumPy performs element-wise operations without loops (vectorization). Broadcasting automatically expands smaller arrays to match larger ones.


In [ ]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(a + b)    # [11 22 33 44] — element-wise addition
print(a * b)    # [ 10  40  90 160] — element-wise multiplication
print(a ** 2)   # [ 1  4  9 16] — square each element
print(a * 10)   # [10 20 30 40] — broadcasting: scalar × array


In [78]:
studentMarks = np.array([25 , 50, 80 , 90 ,10 , 33])
# 80 > A
# 80 < B
# 50 < C
# 33 <= F 

In [94]:
gradeList = []
for i in studentMarks:
    if i >=80:
        gradeList.append("A")
    elif i<80 and i >= 50:
        gradeList.append("B")
    elif i>= 33 and i < 50:
        gradeList.append("C")
    elif i<=33:
        gradeList.append("F")
gradeArray = np.array(gradeList)


In [95]:
print(studentMarks)
print(gradeArray)

[25 50 80 90 10 33]
['F' 'B' 'A' 'A' 'F' 'C']


In [93]:
studentMarks = np.array([25 , 50, 80 , 90 ,10 , 33])

condition = [(studentMarks >=80),(studentMarks >=50),(studentMarks>=33)]
grade = ["A","B","C"]
gradeArray = np.select(condition,grade,default="F")
print(gradeArray)

['F' 'B' 'A' 'A' 'F' 'C']


## Statistical Functions

NumPy provides many statistical functions that operate on entire arrays:
- `np.mean(arr)`, `np.median(arr)`, `np.std(arr)`
- `np.min(arr)`, `np.max(arr)`, `np.sum(arr)`
- Use `axis=0` for columns, `axis=1` for rows


In [ ]:
data = np.array([12, 45, 23, 67, 34, 89, 15, 42])
print(f"Mean:   {np.mean(data):.2f}")
print(f"Median: {np.median(data):.2f}")
print(f"Std:    {np.std(data):.2f}")
print(f"Min:    {np.min(data)}")
print(f"Max:    {np.max(data)}")
print(f"Sum:    {np.sum(data)}")

# Axis example with 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Row sums:", np.sum(matrix, axis=1))    # [ 6 15]
print("Col sums:", np.sum(matrix, axis=0))    # [5 7 9]


In [14]:
arr

array([[[[  1,   2,   3,   4,   5],
         [  6,   7,   8,   9,  10],
         [ 11,  12,  13,  14,  15],
         [ 16,  17,  18,  19,  20]],

        [[ 21,  22,  23,  24,  25],
         [ 26,  27,  28,  29,  30],
         [ 31,  32,  33,  34,  35],
         [ 36,  37,  38,  39,  40]],

        [[ 41,  42,  43,  44,  45],
         [ 46,  47,  48,  49,  50],
         [ 51,  52,  53,  54,  55],
         [ 56,  57,  58,  59,  60]]],


       [[[ 61,  62,  63,  64,  65],
         [ 66,  67,  68,  69,  70],
         [ 71,  72,  73,  74,  75],
         [ 76,  77,  78,  79,  80]],

        [[ 81,  82,  83,  84,  85],
         [ 86,  87,  88,  89,  90],
         [ 91,  92,  93,  94,  95],
         [ 96,  97,  98,  99, 100]],

        [[101, 102, 103, 104, 105],
         [106, 107, 108, 109, 110],
         [111, 112, 113, 114, 115],
         [116, 117, 118, 119, 120]]]])

In [10]:
arr = np.array(range(1,121)).reshape(2,3,4,5)

In [13]:


condition = [(arr%2 == 0),(arr %2 != 0)]
Even_odds = ["Even","Odd"]
EvenOddArray = np.select(condition,grade,default="UnKnown")
print(EvenOddArray)

[[[['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']
   ['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']]

  [['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']
   ['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']]

  [['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']
   ['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']]]


 [[['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']
   ['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']]

  [['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']
   ['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']]

  [['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']
   ['Odd' 'Even' 'Odd' 'Even' 'Odd']
   ['Even' 'Odd' 'Even' 'Odd' 'Even']]]]


## Random Module

`np.random` generates random numbers for simulations and testing:
- `np.random.randint(low, high, size)` — random integers
- `np.random.rand(d0, d1, ...)` — uniform [0, 1)
- `np.random.randn(d0, d1, ...)` — standard normal distribution


In [ ]:
np.random.seed(42)  # for reproducible results

rand_ints = np.random.randint(1, 101, 10)
print("Random integers:", rand_ints)

rand_3x3 = np.random.rand(3, 3)
print("Random 3x3 matrix:\n", rand_3x3)

normal_data = np.random.randn(1000)
print(f"Mean: {np.mean(normal_data):.4f}, Std: {np.std(normal_data):.4f}")
